feature_extract_enable : 0
point_filter_num : 4
max_iteration : 3
dense_map_enable : 1
filter_size_surf : 0.5
filter_size_map : 0.5
cube_side_length : 1000
debug : 0
grid_size : 40
patch_size : 8
img_enable : 0
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
# TODO: understand
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
# TODO: change
cam_fx: 453.483063
cam_fy: 453.254913
cam_cx: 318.908851
cam_cy: 234.238189

common:
    lid_topic:  "/hesai/pandar"
    imu_topic:  "/alphasense/imu"

preprocess:
    lidar_type: 2 # Livox Avia LiDAR
    scan_line: 32
    scan_rate: 10
    blind: 1 # blind x m disable

mapping:
# TODO: understand why there are so large by default
    acc_cov_scale: 0.2
    gyr_cov_scale: 0.2
    b_acc_cov: 0.0043
    b_gyr_cov: 0.000266
    fov_degree:    360
    extrinsic_T: [ -0.001, -0.00855, 0.055]
    extrinsic_R: [ 0, -1, 0,
                   -1, 0, 0,
                   0, 0, -1 ]

camera:
    img_topic: /alphasense/cam0/image_raw
    # TODO: change (it's probably camera to lidar)
    Rcl: [0.00162756,-0.999991,0.00390957,
         -0.0126748,-0.00392989,-0.999912,
          0.999918,0.00157786,-0.012681]
    Pcl: [0.0409257, 0.0318424, -0.0927219]
    
